### PR TITLE
Update to mayfields jsfit 

### PR DESCRIPTION
**Pull request by jimmykane**

### CODE REVIEW

**Comment by jimmykane** [comment]
Hey @mayfield  thanks for this progress. Would you mind if we merge this here? 

There is a current package on npm (not this one) https://github.com/jimmykane/fit-parser that is used by some projects and eventually this "backfit" will replace the "fit-parser" 

Would be glad if you could join us on the org if you like and push this lib to become a better module :-D 

cc @pierremtb

**Comment by vm-pierre** [comment]
Cool! Looking forward to diving in

**Comment by pierremtb** [comment]
Cool! Looking forward to diving in

**Comment by jimmykane** [comment]
I am also summoning @babgvant here :-) 

Maybe if you @babgvant and @mayfield want to join our slack for this little project feel free to ask :-D

**Comment by mayfield** [comment]
> Hey @mayfield thanks for this progress. Would you mind if we merge this here?
> 
> There is a current package on npm (not this one) https://github.com/jimmykane/fit-parser that is used by some projects and eventually this "backfit" will replace the "fit-parser"
> 
> Would be glad if you could join us on the org if you like and push this lib to become a better module :-D
> 
> cc @pierremtb

Hello @jimmykane,

I certainly don't mind you using my commits however you please.  However, ashamedly I didn't make a concerted effort to maintain backwards compatibility because my target use case was perhaps different than the original libraries intent and I was in a great hurry to see if my use case would even work.  So my changes basically break a lot of things from the original.  For example, I did away with unit conversion and I completely changed the intermediate representation that the decoder produces and the new encoder consumes.  In my haste I also didn't have time to bring forward unit tests or even try this code in a node env (bad I know).  I'm running this in a browser exclusively for my main project https://github.com/saucellc/sauce4strava.

I'd be happy to discuss this a further if you're still interested or you might just want to graft the methodologies i used for the encoding process into your repo by hand so you don't have to undo all my hacking and slashing.  I'm fine with whatever you feel is best.

Thanks for the library.  Open source FTW.

**Comment by mayfield** [comment]
For ref here is how I'm using this lib in my project to generate segment files, https://github.com/SauceLLC/sauce4strava/blob/master/src/site/analysis.js#L2660-L2701

I think it's pretty elegant and easy to use for encoding.  I will admit though that my encoder could be optimized further to reduce decoder memory usage if it did a two pass method to determine when message definition local types could be replaced or even reorganized.

**Comment by jimmykane** [comment]
Hey @mayfield great to hear that. For. the encoding and so on I think @pierremtb  can help better here. 

I am more of the maintainer of the lib (not that @pierremtb ain't) so I am not very familiar with your changes :-) 

I closed the PR due to what you said. Many things broke (but that is ok :-) ) . 

Glad to hear from both of you, while I try to merge another fork :-D

**Comment by jimmykane** [comment]
> For ref here is how I'm using this lib in my project to generate segment files, https://github.com/SauceLLC/sauce4strava/blob/master/src/site/analysis.js#L2660-L2701
> 
> I think it's pretty elegant and easy to use for encoding. I will admit though that my encoder could be optimized further to reduce decoder memory usage if it did a two pass method to determine when message definition local types could be replaced or even reorganized.

BTW: 

This looks great ! Wow!

**Pull request closed without merging**
